# Generated by Django 4.2.16 on 2024-11-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_monthly_salary_customer_monthly_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
    ]
